export default [
  {
    id: 1,
    name: 'Garnet',
    type: 'garnet',
    symbol: 'GEM',
    description: 'Put on your brave faces and become a warrior by using Garnet Gem, strengthening your magical powers to shift the odds in your favor. Victory always falls in the hands of Brave.',
    about:'Garnet Gem is equivalent to 0.02 ETH which unlocks Sphynx Slots Machine and Cryptic Human Roullette along with 100 Supraorbs Casino Chips to start your magical journey.',
    tokenIds: [],
    imageUrl: 'https://ipfs.io/ipfs/QmfGPqYrzsDUjNVDZ3nq7qTNRwQDkNYSuVrYfAeCSWP4Ua',
    externalUrl: 'https://ipfs.io/ipfs/QmfGPqYrzsDUjNVDZ3nq7qTNRwQDkNYSuVrYfAeCSWP4Ua',
    gameAssets: [{ 'name' : 'Creator', 'value' : '0x0D8546187C10729260854444Cd28aA76EDacFE51' }],
    salePrice: '0.02',
    weiPrice: '20000000000000000',
    ethUsdPrice: '',
    creator: '0x0D8546187C10729260854444Cd28aA76EDacFE51',
    isAvailable: false,
    gameAssetDesc: '100 Supra Casino Chips',
    displayUrl: '/gem/garnet',
    color: '#4ce1b6',
  },
  {
    id: 2,
    name: 'Amber',
    type: 'amber',
    symbol: 'GEM',
    description: 'Beautiful amber has the most potent magic, possibly the strongest of all the stones. It is defined as the drops of blood from the heart of mother earth, and some say that amber stones are hardened blood drops of dragons who fought ferocious fights before the realm of humankind.',
    about:'Amber Gem is equivalent to 0.1 ETH which unlocks Sphynx Slots Machine and Cryptic Human Roullette along with 500 Supraorbs Casino Chips to raise the level of winnings in Supraorbs.',
    tokenIds: [],
    imageUrl: 'https://ipfs.io/ipfs/QmXj7L1qMJJLYT6vWFAzBRDYeUggUkDiuLgQLVFsgVDL81',
    externalUrl: 'https://ipfs.io/ipfs/QmXj7L1qMJJLYT6vWFAzBRDYeUggUkDiuLgQLVFsgVDL81',
    gameAssets: [{ 'name' : 'Creator', 'value' : '0x0D8546187C10729260854444Cd28aA76EDacFE51' }],
    salePrice: '0.1',
    weiPrice: '100000000000000000',
    ethUsdPrice: '',
    creator: '0x0D8546187C10729260854444Cd28aA76EDacFE51',
    isAvailable: false,
    gameAssetDesc: '500 Supra Casino Chips',
    displayUrl: '/gem/amber',
    color: '#70bbfd',
  },
  {
    id: 3,
    name: 'Amethyst',
    type: 'amethyst',
    symbol: 'GEM',
    description: 'Feel the divine power of Amethyst Gem and win ultimate streaks on Supraorbs casino that will change your life. Amethyst is used as a shielding amulet, and it nourishes your winnings.',
    about:'Amethyst Gem is equivalent to 0.25 ETH which unlocks Sphynx Slots Machine and Cryptic Human Roullette along with 1000 Supraorbs Casino Chips to win untimate streaks on Supraorbs.',
    tokenIds: [],
    imageUrl: 'https://ipfs.io/ipfs/QmcZvmK6PJibAcBwcYF7hxamixRDFBsFBZtGRmUqXGX127',
    externalUrl: 'https://ipfs.io/ipfs/QmcZvmK6PJibAcBwcYF7hxamixRDFBsFBZtGRmUqXGX127',
    gameAssets: [{ 'name' : 'Creator', 'value' : '0x0D8546187C10729260854444Cd28aA76EDacFE51' }],
    salePrice: '0.25',
    weiPrice: '250000000000000000',
    ethUsdPrice: '',
    creator: '0x0D8546187C10729260854444Cd28aA76EDacFE51',
    isAvailable: false,
    gameAssetDesc: '1000 Supra Casino Chips',
    displayUrl: '/gem/amethyst',
    color: '#f6da6e',
  },
  {
    id: 4,
    name: 'Emerald',
    type: 'emerald',
    symbol: 'GEM',
    description: 'Emerald is a mysterious gem that boosts your confidence and helps players predict the future, restores your luck, and drives you towards winning streaks. Its for those who wish to learn the secrets of magic and penetrate the future.',
    about:'Emerald Gem is equivalent to 0.5 ETH which unlocks Sphynx Slots Machine and Cryptic Human Roullette along with 2500 Supraorbs Casino Chips to predict the future on Supraorbs.',
    tokenIds: [],
    imageUrl: 'https://ipfs.io/ipfs/QmQDNSzDn1yyzx59h3WZN25GC99DpovWsTKYzDgY3ED72W',
    externalUrl: 'https://ipfs.io/ipfs/QmQDNSzDn1yyzx59h3WZN25GC99DpovWsTKYzDgY3ED72W',
    gameAssets: [{ 'name' : 'Creator', 'value' : '0x0D8546187C10729260854444Cd28aA76EDacFE51' }],
    salePrice: '0.5',
    weiPrice: '500000000000000000',
    ethUsdPrice: '',
    creator: '0x0D8546187C10729260854444Cd28aA76EDacFE51',
    isAvailable: false,
    gameAssetDesc: '2500 Supra Casino Chips',
    displayUrl: '/gem/emerald',
    color: '#ff4861',
  },
  {
    id: 5,
    name: 'Opal',
    type: 'opal',
    symbol: 'GEM',
    description: 'Opal is the most unpredictable stone, a symbol of ever-changing fortune. It holds the mystical power of all colors of the spectrum and shines in the darkness. The favorite stone of magicians and alchemists around the world. At once, it displays the piercing fire of the ruby, the purple brilliancy of amethyst, and the sea-green emerald, the whole blended and refulgent with a brightness that is quite incredible.',
    about:'Opal Gem is equivalent to 1 ETH which unlocks Sphynx Slots Machine and Cryptic Human Roullette along with 5000 Supraorbs Casino Chips to win with the speed of light.',
    tokenIds: [],
    imageUrl: 'https://ipfs.io/ipfs/QmXuJr6t9YuCc6BLRhz35PcEjnKGiH9ZqN2xGb6Ppg8qN5',
    externalUrl: 'https://ipfs.io/ipfs/QmXuJr6t9YuCc6BLRhz35PcEjnKGiH9ZqN2xGb6Ppg8qN5',
    gameAssets: [{ 'name' : 'Creator', 'value' : '0x0D8546187C10729260854444Cd28aA76EDacFE51' }],
    salePrice: '1',
    weiPrice: '1000000000000000000',
    ethUsdPrice: '',
    creator: '0x0D8546187C10729260854444Cd28aA76EDacFE51',
    isAvailable: false,
    gameAssetDesc: '5000 Supra Casino Chips',
    displayUrl: '/gem/opal',
    color: '#FF33C4',
  },
  {
    id: 6,
    name: 'Ruby',
    type: 'ruby',
    symbol: 'GEM',
    description: 'This ruby Gem - known since ancient times for its magical powers and miracles. The diamond gem properties are so varied that it can be counted among the most vital magical stones. A ruby is recognized as a magical stone of great power that enhances all the energy on Supraorbs. ',
    about:'Ruby Gem is equivalent to 2 ETH which unlocks Sphynx Slots Machine and Cryptic Human Roullette along with 9000 Supraorbs Casino Chips to win huge jackpots every day.',
    tokenIds: [],
    imageUrl: 'https://ipfs.io/ipfs/QmZYkmaU8HA9H66pgygS7YCa9mtMAt8abeYPBCVua9LZCG',
    externalUrl: 'https://ipfs.io/ipfs/QmZYkmaU8HA9H66pgygS7YCa9mtMAt8abeYPBCVua9LZCG',
    gameAssets: [{ 'name' : 'Creator', 'value' : '0x0D8546187C10729260854444Cd28aA76EDacFE51' }],
    salePrice: '2',
    weiPrice: '2000000000000000000',
    ethUsdPrice: '',
    creator: '0x0D8546187C10729260854444Cd28aA76EDacFE51',
    isAvailable: false,
    gameAssetDesc: '9000 Supra Casino Chips',
    displayUrl: '/gem/ruby',
    color: '#222596 ',
  },
];
